name: Locally build the esp-idf firmware.

on: [push]

jobs:
  build_and_flash:
    runs-on: self-hosted

    steps:
      - name: make user own files before checkout
        run: sudo chown -R $(whoami) $HOME/actions-runner
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: esp-idf build
        run: |
          . $HOME/esp/esp-idf/export.sh
          idf.py fullclean
          idf.py build
      - name: make user own files after build
        run: sudo chown -R $(whoami) $HOME/actions-runner
